package pikatweet;


 
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Macbook-Air
 */
public class tweetpopup extends javax.swing.JDialog {

    /**
     * Creates new form tweetpopup
     */
    public tweetpopup(java.awt.Frame parent, boolean modal) throws IOException, FileNotFoundException, ClassNotFoundException{
        super(parent, modal);
        this.username = newOne.readFromFile();
        y = 0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        tweet = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 220, -1));

        label1.setBackground(new java.awt.Color(255, 0, 0));
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Type a tweet:");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        tweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tweetActionPerformed(evt);
            }
        });
        getContentPane().add(tweet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 380, 90));

        jButton1.setText("Tweet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 130, -1));

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Private");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 3, 90, 30));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 130));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 130, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("jLabel4");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 400, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweetActionPerformed

    }//GEN-LAST:event_tweetActionPerformed
    Accounts account;
    String username;
    SaveLoggedInUsername newOne = new SaveLoggedInUsername();
       
   

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            Scanner input = new Scanner(System.in);                          
            FileStorage fs = new FileStorage();
            ArrayList<Accounts> AllUsers = new ArrayList(0);
            
        try {
            AllUsers = fs.retrieveAllUserInfoInUniverse();
        } catch (IOException ex) {
            Logger.getLogger(tweetpopup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(tweetpopup.class.getName()).log(Level.SEVERE, null, ex);
        }
           
            
            
        try {
            PikaTweetLoggedin dialog = new PikaTweetLoggedin(new javax.swing.JFrame(), false, username);
        } catch (IOException ex) {
            Logger.getLogger(tweetpopup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(tweetpopup.class.getName()).log(Level.SEVERE, null, ex);
        }
            

            for(int i = 0; i < AllUsers.size(); i++){
                if(AllUsers.get(i).getUsername().equals(username)){
                    account = AllUsers.get(i);
                }
            }            
            String tweet2 = tweet.getText();
            
            if (tweet2.length() > 140) {
                tweet.setText(null);
                tweet2 = tweet.getText();
                y = 1;
                
            try {
                setVisible(false);
                tweetpopup dialog2 = new tweetpopup(new javax.swing.JFrame(), true);
                dialog2.jLabel7.setText("You have more than 140 characters");
                dialog2.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(PikaTweetLoggedin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PikaTweetLoggedin.class.getName()).log(Level.SEVERE, null, ex);
            }  
            }
            if (y == 0){
            Tweet nub1 = new Tweet(tweet2, privat, username);
            account.addNewTweet(nub1);
            for (int i = 0; i < AllUsers.size(); i++) {
                if(AllUsers.get(i).getUsername().equals(username)){
                    AllUsers.remove(i);
                    AllUsers.add(account);
                }
            }
            try {
                fs.updateAllUsersInfoInUniverse(AllUsers);
            } catch (IOException ex) {
                Logger.getLogger(tweetpopup.class.getName()).log(Level.SEVERE, null, ex);
            }


                setVisible(false);

                }
    }//GEN-LAST:event_jButton1ActionPerformed
boolean privat = false;
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()){
            privat = true;
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void setUsername(String uname){
        username = uname;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tweetpopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tweetpopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tweetpopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tweetpopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    tweetpopup dialog = new tweetpopup(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(tweetpopup.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(tweetpopup.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private java.awt.Label label1;
    private javax.swing.JTextField tweet;
    // End of variables declaration//GEN-END:variables
int y = 0;
}
